# Generated by Django 4.2.8 on 2023-12-14 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, upload_to='brand_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('chexol', 'Chexol'), ('naushnik', 'Naushnik'), ('zaryadnik', 'Zaryadka'), ('boshqa', 'Boshqalar')], max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='%\\da')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='main.brand')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.device')),
            ],
        ),
    ]
