# Generated by Django 4.2.4 on 2023-11-09 09:55

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('head_coach', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='club_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('position', models.CharField(choices=[('gk', 'GoalKeeper'), ('df', 'Defender'), ('mid', 'Middle defender'), ('fw', 'Forward'), ('st', 'Striker')], max_length=50)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='players.club')),
            ],
        ),
    ]
