# Generated by Django 4.2.4 on 2023-10-09 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='published_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 10, 9, 5, 20, 17, 851326, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
