# Generated by Django 4.2.4 on 2023-10-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='published_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
