# Generated by Django 4.2.4 on 2023-10-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_published_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Movie views'),
        ),
    ]
