# Generated by Django 4.2.4 on 2023-10-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_profile_favorites_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='related_movies',
            field=models.ManyToManyField(to='movies.movie'),
        ),
    ]
