# Generated by Django 4.2.4 on 2023-10-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_related_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='related_movies',
            field=models.ManyToManyField(blank=True, to='movies.movie'),
        ),
    ]
