# Generated by Django 4.2.4 on 2023-09-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.ManyToManyField(related_name='services', to='main.service'),
        ),
        migrations.AlterField(
            model_name='order',
            name='worker',
            field=models.ManyToManyField(related_name='workers', to='main.worker'),
        ),
    ]
