# Generated by Django 4.2.4 on 2023-09-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
