# Generated by Django 4.2.5 on 2023-09-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_output_workers_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='debt',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
