# Generated by Django 4.2.5 on 2023-09-25 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_worker_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='workers_debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_debt', to='main.worker'),
        ),
    ]
