# Generated by Django 4.2.4 on 2023-10-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('users', '0005_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='technology',
            field=models.ManyToManyField(related_name='user_technologies', to='forum.tag'),
        ),
    ]
