# Generated by Django 4.2.4 on 2023-10-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('users', '0006_user_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='technology',
            field=models.ManyToManyField(blank=True, related_name='user_technologies', to='forum.tag'),
        ),
    ]
