# Generated by Django 4.2.4 on 2023-11-21 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Muallif ismini kiriting.', max_length=100, verbose_name='Kitob muallifi')),
                ('date_of_birthday', models.DateField(blank=True, help_text="Tug'ilgan sanasini kiriting.", null=True, verbose_name="Tug'ilgan sanasi")),
                ('date_of_death', models.DateField(blank=True, help_text='Vafot etgan sanasini kiriting.', null=True, verbose_name='Vafot etgan sanasi')),
                ('country', models.CharField(blank=True, help_text='Muallif millati.', max_length=100, verbose_name='Millati')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
                ('summary', models.TextField(blank=True, max_length=1000)),
                ('like', models.PositiveSmallIntegerField(default=0)),
                ('dislike', models.PositiveSmallIntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_books', to='main.author')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='main.genre')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.language')),
            ],
        ),
    ]
