# Generated by Django 4.2.4 on 2023-10-24 10:19

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=60, scale=None, size=[570, 400], upload_to='resized_posts/'),
        ),
    ]
